import path from "node:path";
import { ensureDir, writeTextFile } from "./fs-utils";
import { normalizeProjectPath } from "./paths";
import { scanRepository } from "./repo-scan";
import type { LoadedProjectConfig, WorkflowStage } from "./types";

function stageOutputDirectory(config: LoadedProjectConfig, stage: WorkflowStage): string {
  const targetKey = stage.output_target ?? "run_artifact_root";
  return normalizeProjectPath(config.repoRoot, config.manifest[targetKey]);
}

function artifactFileName(artifact: string, feature: string): string {
  const safeFeature = feature.replace(/[^a-zA-Z0-9_-]+/g, "_");
  const nameMap: Record<string, string> = {
    architecture: `architecture_${safeFeature}.md`,
    "code-review": `code_review_${safeFeature}.md`,
    "backend-test-report": `backend_test_report_${safeFeature}.md`,
    "ui-test-report": `ui_test_report_${safeFeature}.md`,
    "release-validation": `release_validation_${safeFeature}.md`,
    "product-doc": `product_doc_${safeFeature}.md`,
    "project-overview": "project_overview.md",
    "solution-map": "solution_map.md",
    "dependency-map": "dependency_map.md",
    "skill-recommendation": "skill_recommendations.md",
    "run-summary": `run_summary_${safeFeature}.md`,
    "implementation-notes": `implementation_notes_${safeFeature}.md`,
    "fix-summary": `fix_summary_${safeFeature}.md`,
  };

  return nameMap[artifact] ?? `${artifact.replace(/[^a-zA-Z0-9_-]+/g, "_")}_${safeFeature}.md`;
}

async function buildArtifactContent(config: LoadedProjectConfig, stage: WorkflowStage, artifact: string, feature: string): Promise<string> {
  if (artifact === "project-overview" || artifact === "solution-map" || artifact === "dependency-map" || artifact === "skill-recommendation") {
    const summary = await scanRepository(config.repoRoot);
    if (artifact === "project-overview") {
      return `# Project Overview: ${config.manifest.project_name}\n\n## Summary\n- Project ID: ${config.manifest.project_id}\n- Repo root: ${config.manifest.root_path}\n- Default workflow: ${config.manifest.default_workflow}\n\n## Repository Shape\n${summary.topLevelEntries.map((entry) => `- ${entry}`).join("\n")}\n\n## Technology Signals\n- Solution files: ${summary.solutionFiles.length}\n- .csproj files: ${summary.csprojFiles.length}\n- package.json files: ${summary.packageJsonFiles.length}\n- Docker files: ${summary.dockerFiles.length}\n\n## Important Docs\n${summary.markdownFiles.slice(0, 15).map((file) => `- ${file}`).join("\n")}\n`;
    }

    if (artifact === "solution-map") {
      return `# Solution Map: ${config.manifest.project_name}\n\n## Solutions And Workspaces\n${summary.solutionFiles.map((file) => `- ${file}`).join("\n") || "- None detected"}\n\n## Backend Projects\n${summary.csprojFiles.map((file) => `- ${file}`).join("\n") || "- None detected"}\n\n## Frontend Projects\n${summary.packageJsonFiles.map((file) => `- ${file}`).join("\n") || "- None detected"}\n`;
    }

    if (artifact === "dependency-map") {
      return `# Dependency Map: ${config.manifest.project_name}\n\n## High-Level Signals\n- Solution files: ${summary.solutionFiles.join(", ") || "None"}\n- Backend projects: ${summary.csprojFiles.length}\n- Frontend packages: ${summary.packageJsonFiles.length}\n- Docker assets: ${summary.dockerFiles.length}\n\n## Notes\n- Review shared DTOs, tenant logic, storage contracts, and search behavior before multi-solution changes.\n`;
    }

    return `# Skill Recommendations: ${config.manifest.project_name}\n\n- Consider enabling stack-specific skills based on detected files.\n- Review solution map before changing cross-cutting areas.\n- Add project-local skill overrides only after human approval.\n`;
  }

  return `# ${artifact}\n\n- Feature: ${feature}\n- Stage: ${stage.id}\n- Role: ${stage.role}\n- Status: Placeholder artifact generated by Helm MVP\n`;
}

export async function writeStageArtifacts(config: LoadedProjectConfig, stage: WorkflowStage, feature: string): Promise<string[]> {
  const outputDir = stageOutputDirectory(config, stage);
  await ensureDir(outputDir);

  const createdFiles: string[] = [];
  for (const artifact of stage.required_artifacts ?? []) {
    const targetPath = path.join(outputDir, artifactFileName(artifact, feature));
    const content = await buildArtifactContent(config, stage, artifact, feature);
    await writeTextFile(targetPath, content);
    createdFiles.push(targetPath);
  }

  return createdFiles;
}