import type { IModelExecutor, ModelExecutionRequest, ModelExecutionResponse } from "./types";

// ---------------------------------------------------------------------------
// Executor registry
// The CLI leaves this undefined (HTTP adapters are used directly).
// The VS Code extension calls registerModelExecutor() on activation so that
// all model calls are routed through vscode.lm without any API keys.
// ---------------------------------------------------------------------------
let _registeredExecutor: IModelExecutor | undefined;

export function registerModelExecutor(executor: IModelExecutor): void {
  _registeredExecutor = executor;
}

interface ModelAdapter {
  execute(request: ModelExecutionRequest): Promise<ModelExecutionResponse>;
}

function resolveModelAlias(model: string): { provider: "openai" | "anthropic" | "google" | "mock"; modelId: string } {
  const normalized = model.toLowerCase();
  if (normalized.startsWith("mock:")) {
    return { provider: "mock", modelId: normalized.slice(5) || "mock" };
  }
  if (normalized.startsWith("gpt")) {
    return { provider: "openai", modelId: process.env.HELM_OPENAI_MODEL_GPT54 ?? model };
  }
  if (normalized.includes("sonnet") || normalized.includes("haiku") || normalized.startsWith("claude")) {
    const aliasMap: Record<string, string> = {
      "sonnet-4.6": process.env.HELM_ANTHROPIC_MODEL_SONNET46 ?? "claude-sonnet-4-6",
      "haiku-4.6": process.env.HELM_ANTHROPIC_MODEL_HAIKU46 ?? "claude-haiku-4-6",
    };
    return { provider: "anthropic", modelId: aliasMap[normalized] ?? model };
  }
  if (normalized.startsWith("gemini")) {
    return { provider: "google", modelId: process.env.HELM_GOOGLE_MODEL_GEMINI ?? model };
  }

  throw new Error(`Unsupported model alias: ${model}`);
}

function extractJsonObject(text: string): string {
  const fencedMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fencedMatch) {
    return fencedMatch[1].trim();
  }

  const start = text.indexOf("{");
  if (start < 0) {
    return text.trim();
  }

  // Count braces to find the matching closing brace
  let braceCount = 0;
  let inString = false;
  let escapeNext = false;

  for (let i = start; i < text.length; i++) {
    const char = text[i];

    if (escapeNext) {
      escapeNext = false;
      continue;
    }

    if (char === "\\") {
      escapeNext = true;
      continue;
    }

    if (char === '"') {
      inString = !inString;
      continue;
    }

    if (!inString) {
      if (char === "{") {
        braceCount++;
      } else if (char === "}") {
        braceCount--;
        if (braceCount === 0) {
          return text.slice(start, i + 1);
        }
      }
    }
  }

  // Fallback if no matching brace found
  return text.slice(start).trim();
}

class MockAdapter implements ModelAdapter {
  async execute(request: ModelExecutionRequest): Promise<ModelExecutionResponse> {
    const artifactMatches = Array.from(request.userPrompt.matchAll(/ARTIFACT_ID: ([a-zA-Z0-9_-]+)/g)).map((match) => match[1]);
    const artifacts = Object.fromEntries(
      artifactMatches.map((artifact) => [artifact, `# ${artifact}\n\nGenerated by mock adapter for model ${request.model}.`]),
    );

    return {
      text: JSON.stringify({
        summary: `Mock execution completed for model ${request.model}.`,
        artifacts,
      }),
      raw: { mock: true },
    };
  }
}

class OpenAIAdapter implements ModelAdapter {
  async execute(request: ModelExecutionRequest): Promise<ModelExecutionResponse> {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      throw new Error("OPENAI_API_KEY is required for GPT models");
    }

    const response = await fetch("https://api.openai.com/v1/responses", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: request.model,
        temperature: request.temperature ?? 0.2,
        max_output_tokens: request.maxTokens ?? 4000,
        input: [
          { role: "system", content: [{ type: "input_text", text: request.systemPrompt }] },
          { role: "user", content: [{ type: "input_text", text: request.userPrompt }] },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`OpenAI request failed: ${response.status} ${await response.text()}`);
    }

    const payload = await response.json() as { output_text?: string };
    return { text: payload.output_text ?? "", raw: payload };
  }
}

class AnthropicAdapter implements ModelAdapter {
  async execute(request: ModelExecutionRequest): Promise<ModelExecutionResponse> {
    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      throw new Error("ANTHROPIC_API_KEY is required for Claude models");
    }

    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: request.model,
        system: request.systemPrompt,
        max_tokens: request.maxTokens ?? 4000,
        temperature: request.temperature ?? 0.2,
        thinking: {
          type: "enabled",
          budget_tokens: 10000,
        },
        messages: [{ role: "user", content: request.userPrompt }],
      }),
    });

    if (!response.ok) {
      throw new Error(`Anthropic request failed: ${response.status} ${await response.text()}`);
    }

    const payload = await response.json() as { content?: Array<{ type: string; text?: string; thinking?: string }> };
    const blocks = payload.content ?? [];
    
    // Extract and log thinking blocks
    const thinkingBlocks = blocks.filter((item) => item.type === "thinking").map((item) => item.text ?? "");
    if (thinkingBlocks.length > 0) {
      console.log("\n[Model Thinking]");
      thinkingBlocks.forEach((thinking) => console.log(thinking));
    }
    
    // Extract text content
    const textBlocks = blocks.filter((item) => item.type === "text").map((item) => item.text ?? "");
    const text = textBlocks.join("\n");
    
    return { text, raw: payload };
  }
}

class GoogleAdapter implements ModelAdapter {
  async execute(request: ModelExecutionRequest): Promise<ModelExecutionResponse> {
    const apiKey = process.env.GOOGLE_API_KEY;
    if (!apiKey) {
      throw new Error("GOOGLE_API_KEY is required for Gemini models");
    }

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${request.model}:generateContent?key=${apiKey}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        systemInstruction: {
          parts: [{ text: request.systemPrompt }],
        },
        contents: [{ parts: [{ text: request.userPrompt }] }],
        generationConfig: {
          temperature: request.temperature ?? 0.2,
          maxOutputTokens: request.maxTokens ?? 4000,
        },
      }),
    });

    if (!response.ok) {
      throw new Error(`Google request failed: ${response.status} ${await response.text()}`);
    }

    const payload = await response.json() as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> };
    const text = payload.candidates?.[0]?.content?.parts?.map((part) => part.text ?? "").join("\n") ?? "";
    return { text, raw: payload };
  }
}

function getAdapter(provider: "openai" | "anthropic" | "google" | "mock"): ModelAdapter {
  switch (provider) {
    case "openai":
      return new OpenAIAdapter();
    case "anthropic":
      return new AnthropicAdapter();
    case "google":
      return new GoogleAdapter();
    case "mock":
      return new MockAdapter();
  }
}

export async function executeModel(request: ModelExecutionRequest): Promise<ModelExecutionResponse> {
  if (_registeredExecutor) {
    return _registeredExecutor.execute(request);
  }
  const resolved = resolveModelAlias(request.model);
  return getAdapter(resolved.provider).execute({ ...request, model: resolved.modelId });
}

export function parseStructuredModelResponse(text: string): { summary: string; artifacts: Record<string, string>; projectFiles: Record<string, string> } {
  let payload: { summary?: string; artifacts?: Record<string, string>; project_files?: Record<string, string> } | undefined;

  // Strategy 1: Try extractJsonObject + JSON.parse (works for clean JSON)
  try {
    payload = JSON.parse(extractJsonObject(text)) as { summary?: string; artifacts?: Record<string, string> };
  } catch {
    // Strategy 2: Try regex-based key extraction for malformed JSON
    // (handles unescaped newlines / markdown inside string values)
    try {
      const summaryMatch = text.match(/"summary"\s*:\s*"((?:[^"\\]|\\.)*)"/);
      const artifactsMatch = text.match(/"artifacts"\s*:\s*\{/);
      if (summaryMatch && artifactsMatch) {
        const artStart = text.indexOf(artifactsMatch[0]);
        const artObjStart = text.indexOf("{", artStart);
        let depth = 0; let inStr = false; let esc = false; let artEnd = -1;
        for (let i = artObjStart; i < text.length; i++) {
          const c = text[i];
          if (esc) { esc = false; continue; }
          if (c === "\\") { esc = true; continue; }
          if (c === '"') { inStr = !inStr; continue; }
          if (!inStr) {
            if (c === "{") depth++;
            else if (c === "}") { depth--; if (depth === 0) { artEnd = i; break; } }
          }
        }
        if (artEnd > 0) {
          const artJson = text.slice(artObjStart, artEnd + 1);
          let artifacts: Record<string, string> = {};
          try { artifacts = JSON.parse(artJson) as Record<string, string>; } catch {
            // Extract keys and treat values as raw markdown
            const keyMatches = [...artJson.matchAll(/"([a-zA-Z0-9_-]+)"\s*:\s*"/g)];
            for (let k = 0; k < keyMatches.length; k++) {
              const key = keyMatches[k][1];
              const valStart = artJson.indexOf('"', keyMatches[k].index! + keyMatches[k][0].length - 1) + 1;
              const nextKey = k + 1 < keyMatches.length ? keyMatches[k + 1].index! : artEnd;
              let raw = artJson.slice(valStart, nextKey);
              raw = raw.replace(/"\s*,?\s*$/, "").replace(/"\s*}\s*$/, "");
              raw = raw.replace(/\\n/g, "\n").replace(/\\t/g, "\t").replace(/\\"/g, '"').replace(/\\\\/g, "\\");
              artifacts[key] = raw;
            }
          }
          payload = {
            summary: summaryMatch[1].replace(/\\n/g, "\n").replace(/\\"/g, '"'),
            artifacts,
          };
        }
      }
    } catch { /* fall through to strategy 3 */ }

    // Strategy 3: If model returned pure markdown (no JSON wrapper), wrap it
    if (!payload) {
      const trimmed = text.trim();
      if (trimmed.startsWith("#") || trimmed.startsWith("```") || !trimmed.startsWith("{")) {
        const headingMatch = trimmed.match(/^#\s+(.+)/m);
        payload = {
          summary: headingMatch ? headingMatch[1] : trimmed.slice(0, 500),
          artifacts: { content: trimmed },
        };
      }
    }

    if (!payload) {
      throw new Error(
        `Model returned non-JSON output. Expected {"summary":"...","artifacts":{...}}. Raw response (first 500 chars): ${text.slice(0, 500)}`,
      );
    }
  }

  return {
    summary: payload.summary ?? "",
    artifacts: payload.artifacts ?? {},
    projectFiles: payload.project_files ?? {},
  };
}